# Generated by Django 3.1.7 on 2021-04-07 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True, verbose_name='Имя')),
                ('complexity', models.PositiveSmallIntegerField(default=50, verbose_name='Сложность')),
            ],
            options={
                'verbose_name': 'язык',
                'verbose_name_plural': 'языки',
                'db_table': 'languages',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
            ],
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=0, verbose_name='Рейтинг')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.language')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.student')),
            ],
        ),
    ]
