# Generated by Django 3.1.7 on 2021-03-24 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('complexity', models.PositiveSmallIntegerField(default=50, verbose_name='complexity')),
            ],
            options={
                'verbose_name': 'язык',
                'verbose_name_plural': 'языки',
                'db_table': 'languages',
            },
        ),
    ]
